# Generated by Django 3.0 on 2021-04-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_tiposdesistemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuaisFabricantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manualNome', models.CharField(blank=True, max_length=255, null=True)),
                ('manualLink', models.CharField(blank=True, max_length=255, null=True)),
                ('manualDescricao', models.CharField(blank=True, max_length=255, null=True)),
                ('manualSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TiposDeSistemas')),
            ],
            options={
                'verbose_name_plural': 'Manuais de Fabricanate',
            },
        ),
    ]
