# Generated by Django 3.0 on 2021-04-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0003_manuaisfabricantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuaisPreventiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventivaEquipamento', models.CharField(blank=True, max_length=255, null=True)),
                ('preventivaProcedimentos', models.CharField(blank=True, max_length=255, null=True)),
                ('preventivaTempo', models.IntegerField(blank=True, null=True)),
                ('preventivaSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TiposDeSistemas')),
            ],
            options={
                'verbose_name_plural': 'Manuais de Preventivas',
            },
        ),
    ]
