# Generated by Django 3.0 on 2021-04-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0004_manuaispreventiva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuaisfabricantes',
            old_name='manualDescricao',
            new_name='fabricanteDescricao',
        ),
        migrations.RenameField(
            model_name='manuaisfabricantes',
            old_name='manualLink',
            new_name='fabricanteLink',
        ),
        migrations.RenameField(
            model_name='manuaisfabricantes',
            old_name='manualNome',
            new_name='fabricanteNome',
        ),
        migrations.RenameField(
            model_name='manuaisfabricantes',
            old_name='manualSistema',
            new_name='fabricanteSistema',
        ),
    ]
