# Generated by Django 3.0 on 2021-04-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0005_auto_20210409_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManuaisFabricantes',
            new_name='ManuaisFabricante',
        ),
    ]
