# Generated by Django 3.0 on 2021-04-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0006_auto_20210409_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhasPadroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senhaEquipamento', models.CharField(blank=True, max_length=255, null=True)),
                ('senhaLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaFabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TiposDeSistemas')),
            ],
            options={
                'verbose_name_plural': ' Senhas Padrão',
            },
        ),
    ]
