# Generated by Django 3.0 on 2021-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0007_senhaspadroes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenhasPadroes',
            new_name='SenhasPadrao',
        ),
    ]
