# Generated by Django 3.0 on 2021-04-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_tiposdesistemas'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamentoNome', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamentoLogin', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamentoPassword', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamentoLocalizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('equipamentoTexto', models.CharField(blank=True, max_length=255, null=True)),
                ('equipamentoSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TiposDeSistemas')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos cliente',
            },
        ),
    ]
