# Generated by Django 3.0 on 2021-04-19 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210419_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 16, 10, 4, 394599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 16, 10, 4, 393600, tzinfo=utc)),
        ),
    ]
