# Generated by Django 3.0 on 2021-04-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componentes', '0002_tiposdesistemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDocumentacao', models.CharField(blank=True, max_length=255, null=True)),
                ('textoDocumentacao', models.CharField(blank=True, max_length=255, null=True)),
                ('sistemaDocumentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TiposDeSistemas')),
            ],
        ),
    ]
