# Generated by Django 3.0 on 2021-04-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacao',
            options={'verbose_name_plural': 'Documentação'},
        ),
    ]
