# Generated by Django 3.0 on 2021-04-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosRespostaForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('respostaForum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.RespostaForum')),
            ],
            options={
                'verbose_name_plural': 'Comentário Resposta',
            },
        ),
    ]
