# Generated by Django 3.0 on 2021-04-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comentariosrespostaforum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariosrespostaforum',
            options={'verbose_name_plural': 'Comentário Respostas'},
        ),
    ]
